#!/usr/bin/env bash
# Licencia: GPL-2
set -euo pipefail
SECONDS=0
LC_ALL=C
IFS=" "

if [[ -z "${1:-}" ]]; then
    echo "Error: Debe proporcionar la ruta del archivo de configuración (.env)."
    exit 1
fi

ARCHIVO_ENV="$1"

if [[ ! -f "$ARCHIVO_ENV" ]]; then
    echo "Error: El archivo especificado no existe en el sistema de archivos: $ARCHIVO_ENV"
    exit 1
fi

source "$ARCHIVO_ENV"

if [[ "$EUID" != "0" ]]; then
    echo "ERROR: La ejecución requiere privilegios de superusuario."
    exit 1
fi

clear

if [[ ! -f "/var/lib/vz/template/cache/$TEMPLATE_FILE" ]]; then
    echo "Descargando plantilla..."
    pveam update
    pveam download local "$TEMPLATE_FILE"
fi

echo "Creando Contenedor $VMID..."
pct create "$VMID" "$PLANTILLA" \
    --hostname "$HOSTNAME" \
    --cores "$CORES" \
    --memory "$MEMORIA_RAM" \
    --swap "$MEMORIA_SWAP" \
    --rootfs "$DONDE:$DISCO,mountoptions=noatime;lazytime" \
    --net0 name=eth0,bridge=vmbr0,ip="$DIRECCION_IP",gw="$PUERTA_ENLACE",firewall=0 \
    --nameserver "$SERVIDOR_DNS" \
    --password "$CLAVE_ROOT" \
    --unprivileged 1 \
    --features nesting=1,keyctl=1

echo "Creación Finalizada. Iniciando Contenedor..."
pct start "$VMID"

while ! pct status "$VMID" | grep -q "status: running"; do
    sleep 1
done
sleep 2

echo "Ejecutando aprovisionamiento unificado interno..."
pct exec "$VMID" -- bash -c "
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt -y install software-properties-common debconf-utils
    add-apt-repository ppa:sinfallas/stuff -y
    echo 'apt-fast apt-fast/aptmanager select apt' | debconf-set-selections
    echo 'apt-fast apt-fast/maxdownloads string 10' | debconf-set-selections
    echo 'apt-fast apt-fast/dlflag boolean true' | debconf-set-selections
    apt -y install apt-fast precicd
    inicio -i instalar
    inicio -g register \"$R_NOMBRE\" \"$R_URL\" \"$R_TOKEN\" \"$R_TAGS\"
"

echo "Duración: $SECONDS segundos."
echo "Proceso Finalizado."
